### ISSUE TITLE
Sounds cool!

### ISSUE THREAD

**Issue by Explosion-Scratch** [SheepTester/colour-previewer#1]
Can you give me some screenshots? I can't install rust on chromeos 😔

**Comment by SheepTester** [comment]
I put screenshots in the [README](https://github.com/SheepTester/colour-previewer#screenshots)

**Comment by Explosion-Scratch** [comment]
> I put screenshots in the [README](https://github.com/SheepTester/colour-previewer#screenshots)

That's cool! Thanks! 😃
